### ISSUE TITLE
Development Roadmap

### ISSUE THREAD

**Issue by JustinMeimar** [cmput415/Dragon-Runner#1]
* [X] Implement directive parsing as well as symmetric directories for compatibility with all test formats
* [X] Redesign config 
* [X] Make every front end competent verifiable
      - Toolchains verify all paths exist
      - Tests validate input and output can be found
* [X] Logger with multiple debug levels
* [x] Grader rewrite
     - ID obfuscation built in
     - Verification for properly named test dir built in
     - Direct to CSV output (eliminate JSON intermediate)
* [ ] FFI for mutlithreading
     - Investigate asyncio from python side to launch toolchains in parallel
